---
# base.yaml
- name: "Base Setup"
  hosts: default
  become: true

  tasks:
  - name: Upgrade installed packages
    apt:
      upgrade: dist
      update_cache: yes

  - name: Remove python2 and pip
    apt:
      pkg:
        - python
        - python-pip
        - python-setuptools
      state: absent

  - name: Install packages
    apt:
      pkg:
        - apt-transport-https
        - ca-certificates
        - cloud-init
        - curl
        - python3
        - python3-pip
        - python3-setuptools
        - software-properties-common
        - unzip
        - virtualenv
      state: latest
      update_cache: yes

  - name: Install pip packages
    pip:
      name:
        - ansible